helm upgrade -n hes-extensions --reuse-values adhoc-response-api elvia-charts/elvia-deployment
helm upgrade -n iss --reuse-values adinfo-extractor elvia-charts/elvia-deployment
helm upgrade -n kvalitetsportalen --reuse-values adinfo-extractor elvia-charts/elvia-deployment
helm upgrade -n fleetmanagement --reuse-values admin elvia-charts/elvia-deployment
helm upgrade -n bildegjennomgang --reuse-values admin-web elvia-charts/elvia-deployment
helm upgrade -n cab-extensions --reuse-values afi-customer elvia-charts/elvia-deployment
helm upgrade -n cab-extensions --reuse-values afi-invbatchref elvia-charts/elvia-deployment
helm upgrade -n cab-extensions --reuse-values afi-invoice elvia-charts/elvia-deployment
helm upgrade -n cab-extensions --reuse-values afi-invoiceline elvia-charts/elvia-deployment
helm upgrade -n cab-extensions --reuse-values afi-invoiperiod elvia-charts/elvia-deployment
helm upgrade -n cab-extensions --reuse-values afi-invotline elvia-charts/elvia-deployment
helm upgrade -n cab-extensions --reuse-values afi-orders elvia-charts/elvia-deployment
helm upgrade -n cab-extensions --reuse-values afi-printtarget elvia-charts/elvia-deployment
helm upgrade -n cab-extensions --reuse-values afi-settlepoint elvia-charts/elvia-deployment
helm upgrade -n cab-extensions --reuse-values afi-vendor elvia-charts/elvia-deployment

helm upgrade -n louvre --reuse-values ai-vision-api elvia-charts/elvia-deployment
helm upgrade -n bad --reuse-values amisite-geo elvia-charts/elvia-deployment
helm upgrade -n sesam-extensions --reuse-values aosjekk elvia-charts/elvia-deployment
helm upgrade -n convey --reuse-values api elvia-charts/elvia-deployment
helm upgrade -n bildegjennomgang --reuse-values api elvia-charts/elvia-deployment
helm upgrade -n uniqueid --reuse-values api elvia-charts/elvia-deployment
helm upgrade -n els --reuse-values api elvia-charts/elvia-deployment
helm upgrade -n doktavle --reuse-values api elvia-charts/elvia-deployment
helm upgrade -n gridtariff --reuse-values api elvia-charts/elvia-deployment
helm upgrade -n emif --reuse-values api elvia-charts/elvia-deployment
helm upgrade -n elsmartextensions --reuse-values api elvia-charts/elvia-deployment
helm upgrade -n idgen --reuse-values api elvia-charts/elvia-deployment
helm upgrade -n sluttbrukeravbrudd --reuse-values api elvia-charts/elvia-deployment
helm upgrade -n fleetmanagement --reuse-values arcgis-api elvia-charts/elvia-deployment
helm upgrade -n deviationimport --reuse-values arcgis-cloud-worker elvia-charts/elvia-deployment
helm upgrade -n bad --reuse-values arcgis-in-dnan elvia-charts/elvia-deployment
helm upgrade -n bad --reuse-values arcgis-in-dnan-intility elvia-charts/elvia-deployment
helm upgrade -n drops --reuse-values archiver elvia-charts/elvia-deployment
helm upgrade -n adls --reuse-values arkiv-api elvia-charts/elvia-deployment
helm upgrade -n adls --reuse-values arkiv-ui elvia-charts/elvia-deployment
helm upgrade -n nettanalyse --reuse-values autonettmelding-api elvia-charts/elvia-deployment
helm upgrade -n nettanalyse --reuse-values autonettmelding-api-intility elvia-charts/elvia-deployment
helm upgrade -n adls --reuse-values avbrudd-detektor elvia-charts/elvia-deployment
helm upgrade -n nettinfra --reuse-values avvik-arcgisimport elvia-charts/elvia-deployment
helm upgrade -n monitoring --reuse-values azure-metrics-extractor elvia-charts/elvia-deployment
helm upgrade -n iss --reuse-values azure-search-indexer elvia-charts/elvia-deployment
helm upgrade -n kvalitetsportalen --reuse-values azure-search-indexer elvia-charts/elvia-deployment

helm upgrade -n ebad --reuse-values bigquery-backfiller elvia-charts/elvia-deployment
helm upgrade -n bad --reuse-values bigquery-in-alarmsandevents elvia-charts/elvia-deployment
helm upgrade -n bad --reuse-values bigquery-in-amsaxmlparser-ideenova elvia-charts/elvia-deployment
helm upgrade -n bad --reuse-values bigquery-in-handata-ideenova elvia-charts/elvia-deployment
helm upgrade -n bad --reuse-values bigquery-in-nanstatistics elvia-charts/elvia-deployment
helm upgrade -n bad --reuse-values bigquery-in-poweroutage elvia-charts/elvia-deployment
helm upgrade -n bad --reuse-values bigquery-in-qualityreadings elvia-charts/elvia-deployment
helm upgrade -n bad --reuse-values bigquery-in-sierra elvia-charts/elvia-deployment
helm upgrade -n bad --reuse-values bigquery-in-topology elvia-charts/elvia-deployment
helm upgrade -n bad --reuse-values bigquery-jobs-backfiller elvia-charts/elvia-deployment
helm upgrade -n bad --reuse-values bigquery-jobs-slapercentiles elvia-charts/elvia-deployment
helm upgrade -n nettinfra --reuse-values bildegjennomgang elvia-charts/elvia-deployment
helm upgrade -n nettinfra --reuse-values bildegjennomgang-admin elvia-charts/elvia-deployment
helm upgrade -n nettinfra --reuse-values bildegjennomgang-api elvia-charts/elvia-deployment
helm upgrade -n cab-extensions --reuse-values cab-inn-01-metrics-extractor elvia-charts/elvia-deployment
helm upgrade -n gridtariff --reuse-values cache elvia-charts/elvia-deployment
helm upgrade -n mdmx --reuse-values calculation-scheduler elvia-charts/elvia-deployment
helm upgrade -n sluttbrukeravbrudd --reuse-values calculator elvia-charts/elvia-deployment
helm upgrade -n bad --reuse-values cdf-in-measurements elvia-charts/elvia-deployment
helm upgrade -n drops --reuse-values classification-worker elvia-charts/elvia-deployment
helm upgrade -n drops --reuse-values classifiercorrelator elvia-charts/elvia-deployment
helm upgrade -n mdmx --reuse-values cloudevent-publisher elvia-charts/elvia-deployment
helm upgrade -n msim --reuse-values cloudevents elvia-charts/elvia-deployment
helm upgrade -n mdmx --reuse-values cloudevents-publisher elvia-charts/elvia-deployment
helm upgrade -n fleetmanagement --reuse-values cronjobs elvia-charts/elvia-deployment
helm upgrade -n jordfeil --reuse-values dashboard elvia-charts/elvia-deployment
helm upgrade -n edna --reuse-values data-api elvia-charts/elvia-deployment
helm upgrade -n edna --reuse-values data-web elvia-charts/elvia-deployment
helm upgrade -n adls --reuse-values datanav-eksport elvia-charts/elvia-deployment
helm upgrade -n edna --reuse-values dataproduct-polling-worker elvia-charts/elvia-deployment
helm upgrade -n nettinfra --reuse-values datascheduler-api elvia-charts/elvia-deployment
helm upgrade -n mdmx --reuse-values dayseries-receiver elvia-charts/elvia-deployment
helm upgrade -n edna --reuse-values dbt-artifact-collector elvia-charts/elvia-deployment
helm upgrade -n mmm --reuse-values deliverysite-api elvia-charts/elvia-deployment
helm upgrade -n mdmx --reuse-values deliveryworker elvia-charts/elvia-deployment
helm upgrade -n core --reuse-values demo-api elvia-charts/elvia-deployment
helm upgrade -n core --reuse-values demo-app elvia-charts/elvia-deployment
helm upgrade -n edna --reuse-values democonsumer elvia-charts/elvia-deployment
helm upgrade -n edna --reuse-values demopublisher elvia-charts/elvia-deployment
helm upgrade -n mdmx --reuse-values deviation-receiver elvia-charts/elvia-deployment
helm upgrade -n nettinfra --reuse-values deviation-risk elvia-charts/elvia-deployment
helm upgrade -n deviationimport --reuse-values deviationrisk-cloud-worker elvia-charts/elvia-deployment
helm upgrade -n ifs-extensions --reuse-values document-api elvia-charts/elvia-deployment
helm upgrade -n nettinfra --reuse-values doktavla elvia-charts/elvia-deployment
helm upgrade -n nettinfra --reuse-values doktavla-api elvia-charts/elvia-deployment
helm upgrade -n doktavle --reuse-values doktavla-api elvia-charts/elvia-deployment
helm upgrade -n doktavle --reuse-values doktavla-ui elvia-charts/elvia-deployment
helm upgrade -n nettinfra --reuse-values doktavla-worker elvia-charts/elvia-deployment
helm upgrade -n edna --reuse-values dp-metrics-extractor elvia-charts/elvia-deployment
helm upgrade -n drops --reuse-values drops-api elvia-charts/elvia-deployment
helm upgrade -n drops --reuse-values drops-ui elvia-charts/elvia-deployment
helm upgrade -n drops --reuse-values drops-worker elvia-charts/elvia-deployment
helm upgrade -n kvalitetsportalen --reuse-values dummy-pushreceiver-api elvia-charts/elvia-deployment
helm upgrade -n iss --reuse-values dummy-pushreceiver-api elvia-charts/elvia-deployment

helm upgrade -n monitoring --reuse-values edna-azurecostwriter elvia-charts/elvia-deployment
helm upgrade -n monitoring --reuse-values edna-k8susagewriter elvia-charts/elvia-deployment
helm upgrade -n monitoring --reuse-values edna-systemwriter elvia-charts/elvia-deployment
helm upgrade -n leveransemotor --reuse-values edna-writer elvia-charts/elvia-deployment
helm upgrade -n fakturadistribusjon --reuse-values ehf-api elvia-charts/elvia-deployment
helm upgrade -n bad --reuse-values elhub-ingress elvia-charts/elvia-deployment
helm upgrade -n mmm --reuse-values elhub-sender elvia-charts/elvia-deployment
helm upgrade -n mmm --reuse-values elhub-subscriber elvia-charts/elvia-deployment
helm upgrade -n mmm --reuse-values elhub-subscriber-metervalues elvia-charts/elvia-deployment
helm upgrade -n mmm --reuse-values elhubmessagepublisher elvia-charts/elvia-deployment
helm upgrade -n els --reuse-values els-web elvia-charts/elvia-deployment
helm upgrade -n elvia-deployment-jt0dtk92pc --reuse-values elvia-deployment-jt0dtk92pc elvia-charts/elvia-deployment
helm upgrade -n elvid --reuse-values elvid elvia-charts/elvia-deployment
helm upgrade -n elvid --reuse-values elvid-admin elvia-charts/elvia-deployment
helm upgrade -n fleetmanagement --reuse-values engineer-api elvia-charts/elvia-deployment
helm upgrade -n mmm --reuse-values estimatedannualconsumption-inn elvia-charts/elvia-deployment
helm upgrade -n fairlight --reuse-values eventhub-copier-alarmsandevents elvia-charts/elvia-deployment
helm upgrade -n fairlight --reuse-values eventhub-copier-measurements elvia-charts/elvia-deployment
helm upgrade -n fairlight --reuse-values eventhub-copier-nanstatistics elvia-charts/elvia-deployment
helm upgrade -n fairlight --reuse-values eventhub-copier-networkquality elvia-charts/elvia-deployment
helm upgrade -n fairlight --reuse-values eventhub-copier-poweroutage elvia-charts/elvia-deployment
helm upgrade -n fairlight --reuse-values eventhub-copier-qualityreadings elvia-charts/elvia-deployment
helm upgrade -n fairlight --reuse-values eventhub-copier-topology elvia-charts/elvia-deployment
helm upgrade -n hes-extensions --reuse-values events-api elvia-charts/elvia-deployment
helm upgrade -n hes-extensions --reuse-values events-spontaneous-api elvia-charts/elvia-deployment
helm upgrade -n datascience --reuse-values eventsdisplay elvia-charts/elvia-deployment
helm upgrade -n aqua --reuse-values example-weatherforecast elvia-charts/elvia-deployment
helm upgrade -n core --reuse-values example-weatherforecast elvia-charts/elvia-deployment
helm upgrade -n kvalitetsportalen --reuse-values exceptioninvocations-ingester elvia-charts/elvia-deployment
helm upgrade -n iss --reuse-values exceptioninvocations-ingester elvia-charts/elvia-deployment
helm upgrade -n kvalitetsportalen --reuse-values exceptioninvocations-ingester-low-priority elvia-charts/elvia-deployment
helm upgrade -n iss --reuse-values exceptioninvocations-ingester-low-priority elvia-charts/elvia-deployment
helm upgrade -n kunde-extensions --reuse-values external-data-api elvia-charts/elvia-deployment
helm upgrade -n kvalitetsportalen --reuse-values external-portal-api elvia-charts/elvia-deployment

helm upgrade -n louvre --reuse-values face-recognition-api elvia-charts/elvia-deployment
helm upgrade -n kunde --reuse-values faktura-api elvia-charts/elvia-deployment
helm upgrade -n nettinfra --reuse-values fleetmanagement-admin elvia-charts/elvia-deployment
helm upgrade -n nettinfra --reuse-values fleetmanagement-arcgis-api elvia-charts/elvia-deployment
helm upgrade -n nettinfra --reuse-values fleetmanagement-cronjobs elvia-charts/elvia-deployment
helm upgrade -n nettinfra --reuse-values fleetmanagement-engineer-api elvia-charts/elvia-deployment
helm upgrade -n nettinfra --reuse-values fleetmanagement-guard-systems elvia-charts/elvia-deployment
helm upgrade -n nettinfra --reuse-values fleetmanagement-gui elvia-charts/elvia-deployment
helm upgrade -n datascience --reuse-values forecastgui elvia-charts/elvia-deployment
helm upgrade -n datascience --reuse-values forecastsubstation elvia-charts/elvia-deployment
helm upgrade -n freshdesk-extensions --reuse-values freshdesk-sms-pusher elvia-charts/elvia-deployment
helm upgrade -n core --reuse-values github-auditor elvia-charts/elvia-deployment
helm upgrade -n core --reuse-values github-repository-team-adder elvia-charts/elvia-deployment
helm upgrade -n core --reuse-values github-webhooks-receiver elvia-charts/elvia-deployment
helm upgrade -n core --reuse-values google-syncer elvia-charts/elvia-deployment
helm upgrade -n kunde --reuse-values grid-tariff-api elvia-charts/elvia-deployment
helm upgrade -n gridtariff --reuse-values gridtariff-meteringpointtariff-sync-worker elvia-charts/elvia-deployment
helm upgrade -n gridtariff --reuse-values gridtariff-priceconfig-api elvia-charts/elvia-deployment
helm upgrade -n fleetmanagement --reuse-values guard-systems-reader elvia-charts/elvia-deployment
helm upgrade -n fleetmanagement --reuse-values gui elvia-charts/elvia-deployment
helm upgrade -n hemmeligkunde --reuse-values hemmeligkunde-api elvia-charts/elvia-deployment
helm upgrade -n hemmeligkunde --reuse-values hemmeligkunde-portal elvia-charts/elvia-deployment
helm upgrade -n bad --reuse-values hesmetervalues-ingress elvia-charts/elvia-deployment
helm upgrade -n bad --reuse-values hesmetervalues-monitoring elvia-charts/elvia-deployment

helm upgrade -n louvre --reuse-values ifs-images elvia-charts/elvia-deployment
helm upgrade -n louvre --reuse-values image-api elvia-charts/elvia-deployment
helm upgrade -n louvre --reuse-values image-rotator elvia-charts/elvia-deployment
helm upgrade -n louvre --reuse-values imageenhance-api elvia-charts/elvia-deployment
helm upgrade -n louvre --reuse-values imageimport-api elvia-charts/elvia-deployment
helm upgrade -n drops --reuse-values in-alarms-and-events elvia-charts/elvia-deployment
helm upgrade -n adls --reuse-values in-anlegg-api elvia-charts/elvia-deployment
helm upgrade -n geonis-extensions --reuse-values in-annualconsumption elvia-charts/elvia-deployment
helm upgrade -n geonis-extensions --reuse-values in-annualconsumption-intility elvia-charts/elvia-deployment
helm upgrade -n louvre --reuse-values in-arcgisimages elvia-charts/elvia-deployment
helm upgrade -n adls --reuse-values in-avbrudd-api elvia-charts/elvia-deployment
helm upgrade -n geonis-extensions --reuse-values in-customer elvia-charts/elvia-deployment
helm upgrade -n ifs-extensions --reuse-values in-customer-intility elvia-charts/elvia-deployment
helm upgrade -n geonis-extensions --reuse-values in-customer-intility elvia-charts/elvia-deployment
helm upgrade -n eltilsyn-extensions --reuse-values in-customerandequipment elvia-charts/elvia-deployment
helm upgrade -n wms-extensions --reuse-values in-customermeterreading-intility elvia-charts/elvia-deployment
helm upgrade -n cab-extensions --reuse-values in-customerprofile elvia-charts/elvia-deployment
helm upgrade -n cab-extensions --reuse-values in-customerprofile-intility elvia-charts/elvia-deployment
helm upgrade -n ifs-extensions --reuse-values in-document-intility elvia-charts/elvia-deployment
helm upgrade -n geonis-extensions --reuse-values in-equipment elvia-charts/elvia-deployment
helm upgrade -n geonis-extensions --reuse-values in-equipment-intility elvia-charts/elvia-deployment
helm upgrade -n ifs-extensions --reuse-values in-equipment-intility elvia-charts/elvia-deployment
helm upgrade -n ifs-extensions --reuse-values in-equipment-measurement-intility elvia-charts/elvia-deployment
helm upgrade -n adls --reuse-values in-hendelse elvia-charts/elvia-deployment
helm upgrade -n ifs-extensions --reuse-values in-lavspent-ncura-intility elvia-charts/elvia-deployment
helm upgrade -n geonis-extensions --reuse-values in-meter elvia-charts/elvia-deployment
helm upgrade -n geonis-extensions --reuse-values in-meter-intility elvia-charts/elvia-deployment
helm upgrade -n quant-extensions --reuse-values in-networkasset-intility elvia-charts/elvia-deployment
helm upgrade -n geonis-extensions --reuse-values in-pole elvia-charts/elvia-deployment
helm upgrade -n geonis-extensions --reuse-values in-pole-intility elvia-charts/elvia-deployment
helm upgrade -n sesam-extensions --reuse-values in-telefoni elvia-charts/elvia-deployment
helm upgrade -n quant-extensions --reuse-values in-workorder-intility elvia-charts/elvia-deployment
helm upgrade -n ifs-extensions --reuse-values in-workorder-intility elvia-charts/elvia-deployment
helm upgrade -n wms-extensions --reuse-values in-workorder-intility elvia-charts/elvia-deployment
helm upgrade -n quant-extensions --reuse-values in-workorderreport-intility elvia-charts/elvia-deployment

helm upgrade -n drops --reuse-values indexer elvia-charts/elvia-deployment
helm upgrade -n mdmx --reuse-values ingress-bqvolumes elvia-charts/elvia-deployment
helm upgrade -n edna --reuse-values ingress-meteringpointversions elvia-charts/elvia-deployment
helm upgrade -n mdmx --reuse-values ingress-meteringpointversions elvia-charts/elvia-deployment
helm upgrade -n mdmx --reuse-values ingress-meterreadings elvia-charts/elvia-deployment
helm upgrade -n ebad --reuse-values ingress-unverifiedmetervolumes elvia-charts/elvia-deployment
helm upgrade -n mdmx --reuse-values ingress-vee-metervalues elvia-charts/elvia-deployment
helm upgrade -n mdmx --reuse-values ingress-volumereadings elvia-charts/elvia-deployment
helm upgrade -n mdmx --reuse-values ingress-workorder-readings elvia-charts/elvia-deployment
helm upgrade -n leveransemotor --reuse-values jira-scraper elvia-charts/elvia-deployment
helm upgrade -n jordfeil --reuse-values jordfeillive elvia-charts/elvia-deployment
helm upgrade -n sesam --reuse-values kafka-consumer elvia-charts/elvia-deployment
helm upgrade -n sesam --reuse-values kafka-publisher elvia-charts/elvia-deployment
helm upgrade -n arcgisunextensions --reuse-values kafka-publisher elvia-charts/elvia-deployment
helm upgrade -n edna --reuse-values kafka-rest-proxy elvia-charts/elvia-deployment
helm upgrade -n drops --reuse-values kpi-updater elvia-charts/elvia-deployment
helm upgrade -n drops --reuse-values kpi-updater-alarmsandevents elvia-charts/elvia-deployment
helm upgrade -n drops --reuse-values kpi-updater-amidevice elvia-charts/elvia-deployment
helm upgrade -n drops --reuse-values kpi-updater-amisite elvia-charts/elvia-deployment
helm upgrade -n drops --reuse-values kpi-updater-metervalues elvia-charts/elvia-deployment
helm upgrade -n drops --reuse-values kpi-updater-radionetwork elvia-charts/elvia-deployment
helm upgrade -n kunde --reuse-values kunde-api elvia-charts/elvia-deployment
helm upgrade -n kunde-extensions --reuse-values kunde-reporting-consumer elvia-charts/elvia-deployment
helm upgrade -n kunde --reuse-values kunde-slack-app elvia-charts/elvia-deployment
helm upgrade -n datascience --reuse-values loadforecast elvia-charts/elvia-deployment
helm upgrade -n louvre --reuse-values louvre-metrics-extractor elvia-charts/elvia-deployment
helm upgrade -n arcgis --reuse-values louvre-plugin elvia-charts/elvia-deployment
helm upgrade -n louvre --reuse-values louvre-web elvia-charts/elvia-deployment

helm upgrade -n convey --reuse-values manifold elvia-charts/elvia-deployment
helm upgrade -n emif --reuse-values market-api elvia-charts/elvia-deployment
helm upgrade -n louvre --reuse-values massimporter elvia-charts/elvia-deployment
helm upgrade -n drops --reuse-values mdm-api elvia-charts/elvia-deployment
helm upgrade -n mdmx --reuse-values mdmx-statistics-reporter elvia-charts/elvia-deployment
helm upgrade -n mdmx --reuse-values mdmx-ui elvia-charts/elvia-deployment
helm upgrade -n edna --reuse-values meteringpointfull-api elvia-charts/elvia-deployment
helm upgrade -n gridtariff --reuse-values meteringpointtariff-sync-worker elvia-charts/elvia-deployment
helm upgrade -n afiextensions --reuse-values meters-ingress elvia-charts/elvia-deployment
helm upgrade -n kunde --reuse-values metervalue-api elvia-charts/elvia-deployment
helm upgrade -n mdmx --reuse-values metervalue-api elvia-charts/elvia-deployment
helm upgrade -n ebad --reuse-values metervalue-api elvia-charts/elvia-deployment
helm upgrade -n mdmapi --reuse-values metervalue-api elvia-charts/elvia-deployment
helm upgrade -n kunde --reuse-values metervalue-api-public elvia-charts/elvia-deployment
helm upgrade -n mmm --reuse-values metervalues elvia-charts/elvia-deployment
helm upgrade -n kvalitetsportalen --reuse-values metrics-extractor elvia-charts/elvia-deployment
helm upgrade -n louvre --reuse-values metrics-extractor elvia-charts/elvia-deployment
helm upgrade -n leveransemotor --reuse-values motorapi elvia-charts/elvia-deployment
helm upgrade -n leveransemotor --reuse-values motorweb elvia-charts/elvia-deployment
helm upgrade -n kunde --reuse-values mssql-prometheus-exporter elvia-charts/elvia-deployment
helm upgrade -n mmm --reuse-values nettleie-inn elvia-charts/elvia-deployment
helm upgrade -n nextin --reuse-values nextin elvia-charts/elvia-deployment
helm upgrade -n adls --reuse-values nis-writer elvia-charts/elvia-deployment

helm upgrade -n els --reuse-values ocr elvia-charts/elvia-deployment
helm upgrade -n ofs --reuse-values ofs-ui elvia-charts/elvia-deployment
helm upgrade -n core --reuse-values oracle-worker elvia-charts/elvia-deployment
helm upgrade -n drops --reuse-values orchestrator elvia-charts/elvia-deployment
helm upgrade -n mmm --reuse-values plikt-inn elvia-charts/elvia-deployment
helm upgrade -n louvre --reuse-values plugin-handler-event-trigger-coordinator elvia-charts/elvia-deployment
helm upgrade -n louvre --reuse-values plugin-organizer-api elvia-charts/elvia-deployment
helm upgrade -n louvre --reuse-values plugin-trigger elvia-charts/elvia-deployment
helm upgrade -n kundeplattformpoc --reuse-values poc-api elvia-charts/elvia-deployment
helm upgrade -n idgen --reuse-values portal elvia-charts/elvia-deployment
helm upgrade -n iss --reuse-values portal elvia-charts/elvia-deployment
helm upgrade -n kvalitetsportalen --reuse-values portal elvia-charts/elvia-deployment
helm upgrade -n emif --reuse-values portal elvia-charts/elvia-deployment
helm upgrade -n bildegjennomgang --reuse-values portal-admin-web elvia-charts/elvia-deployment
helm upgrade -n bildedok --reuse-values portal-admin-web elvia-charts/elvia-deployment
helm upgrade -n bildegjennomgang --reuse-values portal-api elvia-charts/elvia-deployment
helm upgrade -n kvalitetsportalen --reuse-values portal-api elvia-charts/elvia-deployment
helm upgrade -n iss --reuse-values portal-api elvia-charts/elvia-deployment
helm upgrade -n mmm --reuse-values portal-api elvia-charts/elvia-deployment
helm upgrade -n kunde --reuse-values portal-api elvia-charts/elvia-deployment
helm upgrade -n idgen --reuse-values portal-api elvia-charts/elvia-deployment
helm upgrade -n bildedok --reuse-values portal-api elvia-charts/elvia-deployment
helm upgrade -n mmm --reuse-values portal-web elvia-charts/elvia-deployment
helm upgrade -n bildedok --reuse-values portal-web elvia-charts/elvia-deployment
helm upgrade -n louvre --reuse-values power-pole-vision-api elvia-charts/elvia-deployment
helm upgrade -n kunde --reuse-values poweroutage-api elvia-charts/elvia-deployment
helm upgrade -n gridtariff --reuse-values priceconfig-api elvia-charts/elvia-deployment

helm upgrade -n bad --reuse-values pushreceiver-bigquery-amidevice elvia-charts/elvia-deployment
helm upgrade -n bad --reuse-values pushreceiver-bigquery-amisite elvia-charts/elvia-deployment
helm upgrade -n bad --reuse-values pushreceiver-bigquery-devicecomponent elvia-charts/elvia-deployment
helm upgrade -n bad --reuse-values pushreceiver-bigquery-deviceconfiguration elvia-charts/elvia-deployment
helm upgrade -n bad --reuse-values pushreceiver-bigquery-devicetopology elvia-charts/elvia-deployment
helm upgrade -n bad --reuse-values pushreceiver-bigquery-mobilenetworkinfo elvia-charts/elvia-deployment
helm upgrade -n bad --reuse-values pushreceiver-bigquery-workorder elvia-charts/elvia-deployment
helm upgrade -n kvalitetsportalen --reuse-values pushreceiver-datagenerator elvia-charts/elvia-deployment
helm upgrade -n iss --reuse-values pushreceiver-datagenerator elvia-charts/elvia-deployment
helm upgrade -n bad --reuse-values pushreceiver-profiledmeterreadings elvia-charts/elvia-deployment
helm upgrade -n bad --reuse-values quant-ingress elvia-charts/elvia-deployment
helm upgrade -n mdmx --reuse-values readingreceiver elvia-charts/elvia-deployment
helm upgrade -n bad --reuse-values realtimeunits-api elvia-charts/elvia-deployment
helm upgrade -n edna --reuse-values run-results-writer elvia-charts/elvia-deployment
helm upgrade -n louvre --reuse-values search-index-updater elvia-charts/elvia-deployment
helm upgrade -n convey --reuse-values sender elvia-charts/elvia-deployment
helm upgrade -n monitoring --reuse-values sesam-prometheus-exporter elvia-charts/elvia-deployment
helm upgrade -n kunde-extensions --reuse-values sf-workorder-consumer elvia-charts/elvia-deployment
helm upgrade -n core --reuse-values skogshorn-dashboard elvia-charts/elvia-deployment
helm upgrade -n core --reuse-values skogshorn-drift-simulator elvia-charts/elvia-deployment
helm upgrade -n core --reuse-values skogshorn-ifs-simulator elvia-charts/elvia-deployment
helm upgrade -n core --reuse-values skogshorn-kunde-address-generator elvia-charts/elvia-deployment
helm upgrade -n core --reuse-values skogshorn-kunde-simulator elvia-charts/elvia-deployment
helm upgrade -n core --reuse-values skogshorn-msi-simulator elvia-charts/elvia-deployment
helm upgrade -n core --reuse-values skogshorn-nett-location-generator elvia-charts/elvia-deployment
helm upgrade -n core --reuse-values skogshorn-nett-simulator elvia-charts/elvia-deployment
helm upgrade -n core --reuse-values skogshorn-simulator-nett elvia-charts/elvia-deployment
helm upgrade -n kunde --reuse-values slack-app elvia-charts/elvia-deployment
helm upgrade -n slick --reuse-values slick-api elvia-charts/elvia-deployment
helm upgrade -n slick --reuse-values slick-web elvia-charts/elvia-deployment
helm upgrade -n sluttbrukeravbrudd --reuse-values sluttbrukeravbrudd-api elvia-charts/elvia-deployment
helm upgrade -n bad --reuse-values smarthomereceiver-futurehome elvia-charts/elvia-deployment
helm upgrade -n louvre --reuse-values smoketest elvia-charts/elvia-deployment
helm upgrade -n sms --reuse-values sms-broker-poll elvia-charts/elvia-deployment
helm upgrade -n ifs-extensions --reuse-values sms-pusher elvia-charts/elvia-deployment
helm upgrade -n freshdesk-extensions --reuse-values sms-pusher elvia-charts/elvia-deployment
helm upgrade -n sms --reuse-values sms-sender elvia-charts/elvia-deployment
helm upgrade -n kunde --reuse-values sms-trigger elvia-charts/elvia-deployment
helm upgrade -n louvre --reuse-values standardinternalprocessor elvia-charts/elvia-deployment
helm upgrade -n mdmx --reuse-values statistics-reporter elvia-charts/elvia-deployment
helm upgrade -n kvalitetsportalen --reuse-values statsaggregator elvia-charts/elvia-deployment
helm upgrade -n iss --reuse-values statsaggregator elvia-charts/elvia-deployment
helm upgrade -n nettinfra --reuse-values stikkledning elvia-charts/elvia-deployment
helm upgrade -n nettinfra --reuse-values stikkledning-admin elvia-charts/elvia-deployment
helm upgrade -n nettinfra --reuse-values stikkledning-image-admin elvia-charts/elvia-deployment
helm upgrade -n nettinfra --reuse-values stikkledning-image-api elvia-charts/elvia-deployment
helm upgrade -n iss --reuse-values storagecleaner elvia-charts/elvia-deployment
helm upgrade -n kvalitetsportalen --reuse-values storagecleaner elvia-charts/elvia-deployment
helm upgrade -n kvalitetsportalen --reuse-values successfulinvocations-ingester elvia-charts/elvia-deployment
helm upgrade -n iss --reuse-values successfulinvocations-ingester elvia-charts/elvia-deployment
helm upgrade -n kvalitetsportalen --reuse-values successfulinvocations-ingester-low-priority elvia-charts/elvia-deployment
helm upgrade -n iss --reuse-values successfulinvocations-ingester-low-priority elvia-charts/elvia-deployment
helm upgrade -n core --reuse-values super-api elvia-charts/elvia-deployment
helm upgrade -n ifs-extensions --reuse-values supportissue-api-intility elvia-charts/elvia-deployment
helm upgrade -n fairlight --reuse-values synthetic-timeseries-data-generator elvia-charts/elvia-deployment
helm upgrade -n core --reuse-values template-test-complex-api elvia-charts/elvia-deployment
helm upgrade -n core --reuse-values template-test-simple-api elvia-charts/elvia-deployment
helm upgrade -n core --reuse-values terraform-cloud-users-access-checker elvia-charts/elvia-deployment
helm upgrade -n core --reuse-values terraform-cloud-users-access-remover elvia-charts/elvia-deployment
helm upgrade -n core --reuse-values terraform-cloud-users-checker elvia-charts/elvia-deployment
helm upgrade -n core --reuse-values terraform-module-doc-generator elvia-charts/elvia-deployment
helm upgrade -n core --reuse-values terraformcloud-webhooks-receiver elvia-charts/elvia-deployment
helm upgrade -n mmm --reuse-values tidsfrist-api elvia-charts/elvia-deployment
helm upgrade -n drops --reuse-values timestore-api elvia-charts/elvia-deployment
helm upgrade -n ofs --reuse-values ui elvia-charts/elvia-deployment
helm upgrade -n bad --reuse-values unverified-volumes-ingress-backfiller elvia-charts/elvia-deployment
helm upgrade -n mdmx --reuse-values vee-api elvia-charts/elvia-deployment
helm upgrade -n bad --reuse-values verified-volumes-ingress-backfiller elvia-charts/elvia-deployment
helm upgrade -n afiextensions --reuse-values verifiedmeteringvolumes-ingress elvia-charts/elvia-deployment
helm upgrade -n bad --reuse-values voltage-api elvia-charts/elvia-deployment
helm upgrade -n bad --reuse-values voltagedashboard elvia-charts/elvia-deployment
helm upgrade -n bad --reuse-values volumes-monitoring elvia-charts/elvia-deployment
helm upgrade -n bad --reuse-values weather-ingest-api elvia-charts/elvia-deployment
helm upgrade -n bad --reuse-values weather-ingest-forecast-feeder elvia-charts/elvia-deployment
helm upgrade -n bad --reuse-values weather-ingest-observations-feeder elvia-charts/elvia-deployment
helm upgrade -n els --reuse-values web elvia-charts/elvia-deployment
helm upgrade -n bildegjennomgang --reuse-values web elvia-charts/elvia-deployment
helm upgrade -n nextin --reuse-values web elvia-charts/elvia-deployment
helm upgrade -n default --reuse-values webapi-chart-testing elvia-charts/elvia-deployment
helm upgrade -n core --reuse-values webhooks-creator elvia-charts/elvia-deployment
helm upgrade -n drops --reuse-values worker elvia-charts/elvia-deployment
helm upgrade -n emif --reuse-values worker-mde elvia-charts/elvia-deployment
helm upgrade -n emif --reuse-values worker-quant elvia-charts/elvia-deployment
helm upgrade -n kunde-extensions --reuse-values workorderpublisher elvia-charts/elvia-deployment
