trigger:
  - '*'

pool:
  vmImage: "ubuntu-latest"

stages:
- stage: HelmPackage
  jobs:
    - job: Package
      pool:
        vmImage: "ubuntu-latest"
      steps:
      
        - task: HelmDeploy@0
          displayName: Helm package
          inputs:
            command: package
            chartPath: elvia-deployment
            destination: $(Build.ArtifactStagingDirectory)
        # Generate kubernetes manifest from Helm chart
        - script: |
            sh "git clone https://github.com/3lvia/kubernetes-charts.git chart-repo"
            sh "cd chart-repo"
            helm package elvia-deployment
            helm repo index .
            git add .
            git commit "Publish new package"
            git push origin trunk
          displayName: Generate new chart package

