trigger:
  - master
  
pr:
  autoCancel: 'true'
  branches:
    include:
      - master

pool:
  vmImage: "ubuntu-20.04"

stages:
- stage: ChartTesting
  jobs:
    - job: RunChartTesting
      steps:
        - script: |
            curl https://baltocdn.com/helm/signing.asc | sudo apt-key add -
            sudo apt-get install apt-transport-https --yes
            echo "deb https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
            sudo apt-get update
            sudo apt-get install helm
          displayName: Install helm 3
        - script: |
            curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.23.0/kind-linux-amd64
            chmod +x ./kind
            sudo mv kind /usr/local/bin
            sudo service docker restart
            kind create cluster --wait 5m
          displayName: Install kubernetes cluster
        - script: |
            helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
            helm repo update
            helm install prometheus prometheus-community/kube-prometheus-stack
          displayName: Helm Install kube-prometheus-stack
        - script: |
            kubectl get events --sort-by='{.lastTimestamp}'
          displayName: kubectl get events
          condition: failed()
        - script: |
            helm repo add traefik https://helm.traefik.io/traefik
            helm install traefik traefik/traefik
          displayName: Install Traefik
        - script: |
            kubectl create namespace core
          displayName: Create namespace core
        - script: |
            kubectl -n core create sa pushreceiver-chart-testing
            kubectl -n core create sa webapi-chart-testing
            kubectl -n core create sa worker-chart-testing
          displayName: Create service accounts
        - script: |
            kubectl get namespace
            kubectl get servicemonitor --all-namespaces
          displayName: Test kubectl
        - script: sudo apt-get install yamllint
          displayName: Install yamllint
        - script: |
            sudo apt-get update 
            sudo pip3 install setuptools
            sudo pip3 install yamale    
          displayName: Install yamale

        - script: |
            mkdir $HOME/.ct
            mv ct/etc/* $HOME/.ct/
            chmod +x ct/bin/ct
          displayName: Configure ct config
          workingDirectory: $(Build.SourcesDirectory)

        - script: ./ct/bin/ct lint --config ct.yaml
          displayName: Run ct lint
          workingDirectory: $(Build.SourcesDirectory)
        - script: ./ct/bin/ct install --upgrade --config ct.yaml
          displayName: Run ct install --upgrade
          workingDirectory: $(Build.SourcesDirectory)

          

          


