---
# Source: elvia-deployment/templates/service.yaml
kind: Service
apiVersion: v1
metadata:
  name: github-repository-team-adder
  namespace: core
  labels:
    app: github-repository-team-adder
spec:
  ports:
  - port: 2112
    name: github-repository-team-adderport
  selector:
    app: github-repository-team-adder

---
# Source: elvia-deployment/templates/service-monitor.yaml
kind: ServiceMonitor
apiVersion: monitoring.coreos.com/v1
metadata:
  name: github-repository-team-adder
  namespace: core
spec:
  endpoints:
  - port: github-repository-team-adderport
  selector:
    matchLabels:
      app: github-repository-team-adder

---
# Source: elvia-deployment/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-repository-team-adder
  namespace: core
spec:
  replicas: 2
  selector:
    matchLabels:
      app: elvid
      microservice-type: webapi
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: elvid
        microservice-type: webapi
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: runtime/default
    spec:
      containers:
      - env:
        null
        image: "containerregistryelvia.azurecr.io/github-repository-team-adder:2.02009212e+07"
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsUser: 1001
          runAsGroup: 1001
          fsGroup: 1001
          supplementalGroups: [1001]
        lifecycle:
          preStop:
            exec:
              command:
              - sleep
              - "15"
        name: elvid
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /.well-known/openid-configuration
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 3
        resources:
          limits:
            cpu: 800m
            memory: 800Mi
          requests:
            cpu: 400m
            memory: 400Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsConfig:
        options:
        - name: single-request-reopen
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: containerregistryprodsecret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: elvid
      serviceAccountName: elvid
      terminationGracePeriodSeconds: 30
