# Default values for elvia-job.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# name: demo-job
# namespace: core
# environment: dev|test|kptest|prod

# backoffLimit: 6
# completions: 1
# parallelism: 1

# image:
#   repository: containerregistryelvia.azurecr.io/core/demo-job
#   tag: latest

# imagePullSecret: containerregistryelvia

# env:
# - name: ASPNETCORE_URLS
#   value: http://+:8080
# - name: my_key_from_config_map
#   valueFrom:
#     configMapKeyRef:
#       key: my_key
#       name: demo-job

# envFrom:
# - name: demo-job

# resources:
#   limits:
#     cpu: 100m
#     memory: 128Mi
#   requests:
#     cpu: 100m
#     memory: 128Mi
#   # per-environment overrides, fall back to resources.limits/requests above when omitted
#   dev:
#     limits:
#       cpu: 100m
#       memory: 128Mi
#   test:
#     limits:
#       cpu: 100m
#       memory: 128Mi
#     requests:
#       cpu: 100m
#       memory: 128Mi
#   prod:
#     limits:
#       cpu: 100m
#       memory: 128Mi
#     requests:
#       cpu: 100m
#       memory: 128Mi

# securityContext:
#   seccompProfile:
#     type: RuntimeDefault
#   runAsUser: 1001
#   runAsGroup: 1001
#   fsGroup: 1001
#   supplementalGroups: [1001]

# labels:
#   repositoryName: my-repo
#   commitHash: abc1234
#   deployedBy: github-actions

# configmap:
#   dev:
#     my_key: my_value

# secret:
#   dev:
#     api_key: '__API_KEY_TO_BE_REPLACED_DEV__'

# accessPolicy:
#   inbound:
#     rules:
#     - namespace: core
#       application: demo-api
#   outbound:
#     rules:
#     - namespace: core
#       application: demo-api
