apiVersion: batch/v1
kind: CronJob
metadata:
  {{- include "elvia-job-common.metadata" . | nindent 2 }}
spec:
  schedule: {{ required "Missing .Values.schedule" .Values.schedule | quote }}
  suspend: {{ .Values.suspend | default false }}
  concurrencyPolicy: {{ .Values.concurrencyPolicy | default "Forbid" }}
  successfulJobsHistoryLimit: {{ .Values.successfulJobsHistoryLimit | default 3 }}
  failedJobsHistoryLimit: {{ .Values.failedJobsHistoryLimit | default 1 }}
  jobTemplate:
    spec:
      {{- include "elvia-job-common.jobSpec" . | nindent 6 }}
