---
name: pushreceiver-chart-testing
namespace: core
microserviceType: pushreceiver
environment: test

replicaCount: 1

image:
  repository: mcr.microsoft.com/dotnet/samples
  tag: aspnetapp

resources:
  requests:
    cpu: "100m"
    memory: "200Mi"
  limits:
    cpu: "150m"
    memory: "0.5Gi"

env:
  - name: Kvalitetsportalen__Environment
    valueFrom:
      configMapKeyRef:
        name: pushreceiver-chart-testing
        key: kvalitetsportalen.environment
  - name: ApplicationInsights__Environment
    valueFrom:
      configMapKeyRef:
        name: pushreceiver-chart-testing
        key: insights.environment
  - name: ELVID__Authority
    valueFrom:
      configMapKeyRef:
        name: pushreceiver-chart-testing
        key: elvid.authority
  - name: ELVID__RequiredScope
    value: pr.sesam
  - name: bigtable__project
    valueFrom:
      configMapKeyRef:
        name: pushreceiver-chart-testing
        key: bigtable.project
  - name: bigtable__instanceid
    valueFrom:
      configMapKeyRef:
        name: pushreceiver-chart-testing
        key: bigtable.instanceid

service:
  port: 80
  targetPort: 8080

ingress:
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefixStrip
    # Redirect the /metrics endpoint to /
    # This ensures that the /metrics endpoint is not open on the internet
    traefik.ingress.kubernetes.io/redirect-permanent: "true"
    traefik.ingress.kubernetes.io/request-modifier: "ReplacePathRegex: ^/.*metrics(.*)$ /"
  subdomain: badapi
  path: "/profiledmeterreadings"

configmap:
  dev:
    kvalitetsportalen.environment: DEV
    elvid.authority: https://elvid.test-elvia.io/
    insights.environment: Dev
    bigtable.project: "hafslund-mdm-dev"
    bigtable.instanceid: "mdm-meterreadings-dev"
  test:
    kvalitetsportalen.environment: AMS-T01
    elvid.authority: https://elvid.test-elvia.io/
    insights.environment: Test
    bigtable.project: "hafslund-mdm-test"
    bigtable.instanceid: "mdm-meterreadings-test"
  prod:
    kvalitetsportalen.environment: HIPAD
    elvid.authority: https://elvid.elvia.io/
    insights.environment: Prod
    bigtable.project: "hafslund-mdm"
    bigtable.instanceid: "mdm-meterreadings"

readinessProbe:
  failureThreshold: 3
  httpGet:
    path: /metrics
    port: 2112
    scheme: HTTP
  initialDelaySeconds: 15
  periodSeconds: 15
  successThreshold: 1
  timeoutSeconds: 3

livenessProbe:
  failureThreshold: 5
  httpGet:
    path: /metrics
    port: 2112
    scheme: HTTP
  initialDelaySeconds: 15
  periodSeconds: 15
  successThreshold: 1
  timeoutSeconds: 3
