---
name: webapi-chart-testing
namespace: core
microserviceType: webapi
environment: dev

replicaCount: 1

dnsConfig:
  options:
  - name: single-request-reopen

hostAliases:
  - ip: "10.160.4.139"
    hostnames:
      - "haarcgeoevent01.hipad.no"
  - ip: "172.19.253.6"
    hostnames:
      - "haarcgeoevt01t1.hipad.no"

image:
  repository: containerregistryelvia.azurecr.io/bad-realtimeunits-api
  tag: "20200715.2"

resources:
  requests:
    cpu: "100m"
    memory: "200Mi"
  limits:
    cpu: "150m"
    memory: "0.5Gi"

service:
  port: 80
  targetPort: 8080

ingress:
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefixStrip
    # Redirect the /metrics endpoint to /
    # This ensures that the /metrics endpoint is not open on the internet
    traefik.ingress.kubernetes.io/redirect-permanent: "true"
    traefik.ingress.kubernetes.io/request-modifier: "ReplacePathRegex: ^/.*metrics(.*)$ /"
  subdomain: badapi
  path: "/"
