{{- if .Values.secret}}

{{- if eq .Values.environment "dev"}}
{{- if .Values.secret.dev }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ required "Missing .Values.name" .Values.name }}
  namespace: {{ required "Missing .Values.namespace" .Values.namespace }}
type: Opaque
stringData: {{- toYaml .Values.secret.dev | nindent 2 }} 
{{- end }}
{{- end }}

{{- if eq .Values.environment "test"}}
{{- if .Values.secret.test }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ required "Missing .Values.name" .Values.name }}
  namespace: {{ required "Missing .Values.namespace" .Values.namespace }}
type: Opaque
stringData: {{- toYaml .Values.secret.test | nindent 2 }} 
{{- end }}
{{- end }}

{{- if eq .Values.environment "dvtest"}}
{{- if .Values.secret.dvtest }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ required "Missing .Values.name" .Values.name }}
  namespace: {{ required "Missing .Values.namespace" .Values.namespace }}
type: Opaque
stringData: {{- toYaml .Values.secret.dvtest | nindent 2 }} 
{{- end }}
{{- end }}

{{- if eq .Values.environment "prod"}}
{{- if .Values.secret.prod }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ required "Missing .Values.name" .Values.name }}
  namespace: {{ required "Missing .Values.namespace" .Values.namespace }}
type: Opaque
stringData: {{- toYaml .Values.secret.prod | nindent 2 }} 
{{- end }}
{{- end }}

{{- end }}
