# Default values for elvia-deployment.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

name: demo-api
namespace: adms-extensions
microserviceType: webapi

replicaCount: 
  dev: 1
  test: 1
  prod: 2

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 100m
    memory: 128Mi

env:
- name: ASPNETCORE_URLS
  value: http://+:8080

podLabels:
  external: activemq

service:
 port: 80
 targetPort: 8080

ingress:
  subdomain: iss # only iss is supported
  path: "/demo-api"

lifecycle:
  preStop:
    exec:
      command:
      - sleep
      - "1"

# serviceMonitor:
#   disableIstio: true

readinessProbe:
  failureThreshold: 3
  httpGet:
    path: /health
    port: 8080
    scheme: HTTP
  initialDelaySeconds: 15
  periodSeconds: 15
  successThreshold: 1
  timeoutSeconds: 3

livenessProbe:
  failureThreshold: 5
  httpGet:
    path: /health
    port: 8080
    scheme: HTTP
  initialDelaySeconds: 15
  periodSeconds: 15
  successThreshold: 1
  timeoutSeconds: 3

startupProbe:
  failureThreshold: 45
  httpGet:
    path: /health
    port: 8080
    scheme: HTTP
  initialDelaySeconds: 5
  periodSeconds: 1
  successThreshold: 1
  timeoutSeconds: 2
