kind: ServiceMonitor
apiVersion: monitoring.coreos.com/v1
metadata:
  name: {{ required "Missing .Values.name" .Values.name }}
  namespace: {{ required "Missing .Values.namespace" .Values.namespace }}
spec:
  endpoints:
  - port: {{ required "Missing .Values.name" .Values.name }}port
    scheme: https
    tlsConfig:
      caFile: /etc/istio-output-certs/root-cert.pem
      certFile: /etc/istio-output-certs/cert-chain.pem
      insecureSkipVerify: true
      keyFile: /etc/istio-output-certs/key.pem
    {{- if .Values.serviceMonitor }}
    {{- if .Values.serviceMonitor.interval }}
    interval: {{ .Values.serviceMonitor.interval -}}
    {{- end }}
    {{- if .Values.serviceMonitor.honorLabels }}
    honorLabels: {{ .Values.serviceMonitor.honorLabels -}}
    {{- end }}
    {{- end }}
  selector:
    matchLabels:
      app: {{ required "Missing .Values.name" .Values.name }}