{{- if .Values.ingress -}}
{{- if and .Values.ingress.exposure (not (has .Values.ingress.exposure (list "internal" "public-ip-filtered" "public"))) }}
{{- fail (printf "Invalid ingress.exposure value: %s. Must be 'public-ip-filtered', 'internal', or 'public', or omit it" .Values.ingress.exposure) }}
{{- end }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ required "Missing .Values.name" .Values.name }}
  namespace: {{ required "Missing .Values.namespace" .Values.namespace }}
  {{- if .Values.ingress.annotations }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  routes:
  - kind: Rule
    {{- if eq .Values.ingress.exposure "internal" }}
    match: Host(`{{ include "ingress.internalHost" . }}`) && PathPrefix(`{{ required "Missing .Values.ingress.path" .Values.ingress.path }}`)
    {{- else }}
    match: Host(`{{ include "ingress.host" . }}`) && PathPrefix(`{{ required "Missing .Values.ingress.path" .Values.ingress.path }}`)
    {{- end }}
    {{- if .Values.ingress.routemiddlewares }}
    middlewares: {{- toYaml .Values.ingress.routemiddlewares | nindent 4 }}
    {{- else }}
    middlewares:
    - name: {{ required "Missing .Values.name" .Values.name }}-stripprefix
    - name: hsts-header
      namespace: dns
    - name: remove-metrics
      namespace: dns
    {{- if eq .Values.ingress.exposure "public-ip-filtered" }}
    - name: {{ required "Missing .Values.name" .Values.name }}-ipwhitelist-internal
      namespace: {{ required "Missing .Values.namespace" .Values.namespace }}
    {{- end }}
    {{- end }}
    services:
      - name: {{ required "Missing .Values.name" .Values.name }}
        {{- if .Values.service.port }}
        port: {{ .Values.service.port }}
        {{- else }}
        port: 80
        {{- end}}
        {{- if .Values.ingress.stickysession }}
        sticky: {{- toYaml .Values.ingress.stickysession | nindent 10 }}
        {{- end}}
  {{- if .Values.ingress.enforceApiManagement}}
  {{- if ne .Values.ingress.subdomain "api"}}
  {{- fail "If ingress.enforceApiManagement is enabled, the subdomain must be api." }}
  {{- end }}
  tls:
    options:
      name: pki
      namespace: vault
  {{- end }}
---
# Strip prefix
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ required "Missing .Values.name" .Values.name }}-stripprefix
  namespace: {{ required "Missing .Values.namespace" .Values.namespace }}
spec:
  stripPrefix:
    prefixes:
      - {{ required "Missing .Values.ingress.path" .Values.ingress.path }}
{{- if eq .Values.ingress.exposure "public-ip-filtered" }}
---
# IP Whitelist-internal
# POC Will be moved to argocd /manifests/cluster-addons/environments/xxxx/xxx/traefik/manifests/middleware.yaml
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ required "Missing .Values.name" .Values.name }}-ipwhitelist-internal
  namespace: {{ required "Missing .Values.namespace" .Values.namespace }}
spec:
  ipAllowList:
    sourceRange:
      - 188.95.241.183/32 #IP for all Elvia machines
    ipStrategy:
      depth: 1

{{- end }}

{{- end }}
