name: ingress-volumereadings
namespace: mdmx
microserviceType: worker

replicaCount: 1

image:
  repository: containerregistryelvia.azurecr.io/mdmx-ingress-volumereadings

sidecars:
  sidecar:
    name: gs2parser
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        cpu: 100m
        memory: 512Mi
    service:
      targetPort: 8080
      port: 80
    image:
      repository: containerregistryelvia.azurecr.io/mdmx-gs2parser

resources:
  requests:
    cpu: 100m
    memory: 512Mi
  limits:
    cpu: 100m
    memory: 512Mi

env:
  - name: VolumeReading__Url
    value: "http://localhost:8080"
  - name: MDMX_API_HOSTNAME
    valueFrom:
      configMapKeyRef:
        name: ingress-volumereadings
        key: mdmxapi.readings.url
  - name: MDMX_API_READINGS_ENDPOINT
    valueFrom:
      configMapKeyRef:
        name: ingress-volumereadings
        key: mdmxapi.readings.endpoint
  - name: MDMX_API_USE_MOCK_CLIENT
    value: "false"

configmap:
  dev:
    mdmxapi.readings.url: "https://mdmx.dev-elvia.io/api"
    mdmxapi.readings.endpoint: "readings"
  test:
    mdmxapi.readings.url: "https://mdmx.test-elvia.io/api"
    mdmxapi.readings.endpoint: "readings"
  prod:
    mdmxapi.readings.url: "https://mdmx.elvia.io/api"
    mdmxapi.readings.endpoint: "readings"