---
parameters:
  - name: helmValuesFile
  - name: name

jobs:
  - deployment: name
    displayName: ${{ parameters.name }}
    environment: dev
    strategy:
      runOnce:
        deploy:
          steps:
            - task: HelmDeploy@0
              displayName: Helm deploy
              inputs:
                connectionType: Kubernetes Service Connection
                kubernetesServiceEndpoint: RuntimeServiceKubernetesDev
                namespace: $(namespace)
                command: upgrade
                failOnStderr: false
                arguments: --debug
                chartName: $(Pipeline.Workspace)/elvia-deployment/
                releaseName: ${{ parameters.name }}
                valueFile: $(Pipeline.Workspace)/CI/${{ parameters.helmValuesFile }}

            - task: Kubernetes@1
              displayName: kubectl rollout status deploy ${{ parameters.name }}
              inputs:
                kubernetesServiceEndpoint: RuntimeServiceKubernetesDev
                namespace: $(namespace)
                command: rollout
                arguments: status deploy ${{ parameters.name }}

            # - task: HelmDeploy@0
            #   displayName: Helm rollback
            #   inputs:
            #     connectionType: Kubernetes Service Connection
            #     kubernetesServiceEndpoint: RuntimeServiceKubernetesDev
            #     namespace: $(namespace)
            #     command: rollback
            #     failOnStderr: false
            #     arguments: ${{ parameters.name }}
