# Default values for elvia-deployment.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# name: github-repository-team-adder
# namespace: core
# microserviceType: worker|webapi|pushreceiver
# environment: dev|test|prod

# replicaCount: 1

# image:
#   repository: containerregistryelvia.azurecr.io/github-repository-team-adder
#   tag: "20200921.2"

# imagePullSecret: containerregistryelvia

# env: 
# - name: ASPNETCORE_URLS
#   value: http://+:8080
# - name: my_key_from_config_map
#   valueFrom:
#     configMapKeyRef:
#       key: my_key
#       name: github-repository-team-adder

# service:
#   port: 80
#   targetPort: 8080

# ingress:
#   annotations: 
#     kubernetes.io/ingress.class: traefik
#     traefik.frontend.rule.type: PathPrefixStrip
#     # Redirect the /metrics endpoint to /
#     # This ensures that the /metrics endpoint is not open on the internet
#     traefik.ingress.kubernetes.io/redirect-permanent: "true"
#     traefik.ingress.kubernetes.io/redirect-regex: ^https://kunde.test-hafslundnett.io/metrics(.*)
#     traefik.ingress.kubernetes.io/redirect-replacement: https://kunde.test-hafslundnett.io/
#   subdomain: github-repository-team-adder
#   path: "/mypath"
#   port: 80 # 80 default

# resources:
#   limits:
#     cpu: 100m
#     memory: 128Mi
#   requests:
#     cpu: 100m
#     memory: 128Mi

# autoscaling:
#   minReplicas: 2
#   maxReplicas: 4
#   targetCPUUtilizationPercentage: 80
