helm mapkubeapis -n adls arkiv-api
helm mapkubeapis -n adls arkiv-ui
helm mapkubeapis -n adls in-anlegg-api
helm mapkubeapis -n adls in-avbrudd-api
helm mapkubeapis -n arcgis louvre-plugin
helm mapkubeapis -n bad amisite-geo
helm mapkubeapis -n bad pushreceiver-bigquery-amidevice
helm mapkubeapis -n bad pushreceiver-bigquery-amisite
helm mapkubeapis -n bad pushreceiver-bigquery-devicecomponent
helm mapkubeapis -n bad pushreceiver-bigquery-deviceconfiguration
helm mapkubeapis -n bad pushreceiver-bigquery-devicetopology
helm mapkubeapis -n bad pushreceiver-bigquery-mobilenetworkinfo
helm mapkubeapis -n bad pushreceiver-bigquery-workorder
helm mapkubeapis -n bad pushreceiver-profiledmeterreadings
helm mapkubeapis -n bad realtimeunits-api
helm mapkubeapis -n bad voltage-api
helm mapkubeapis -n bad voltagedashboard
helm mapkubeapis -n bad weather-ingest-api
helm mapkubeapis -n bildedok portal-admin-web
helm mapkubeapis -n bildedok portal-api
helm mapkubeapis -n bildedok portal-web
helm mapkubeapis -n cab-extensions in-customerprofile
helm mapkubeapis -n cab-extensions in-customerprofile-intility
helm mapkubeapis -n convey api
helm mapkubeapis -n core demo-api
helm mapkubeapis -n core example-weatherforecast
helm mapkubeapis -n core github-webhooks-receiver
helm mapkubeapis -n core pushreceiver-chart-testing
helm mapkubeapis -n core super-api
helm mapkubeapis -n core template-test-complex-api
helm mapkubeapis -n core template-test-simple-api
helm mapkubeapis -n core terraformcloud-webhooks-receiver
helm mapkubeapis -n datascience eventsdisplay
helm mapkubeapis -n datascience forecastsubstation
helm mapkubeapis -n datascience loadforecast
helm mapkubeapis -n deviationimport arcgis-cloud-worker
helm mapkubeapis -n doktavle api
helm mapkubeapis -n doktavle doktavla-api
helm mapkubeapis -n doktavle doktavla-ui
helm mapkubeapis -n drops drops-api
helm mapkubeapis -n drops drops-ui
helm mapkubeapis -n drops drops-ui-nd
helm mapkubeapis -n drops ifs-document-api
helm mapkubeapis -n drops mdm-api
helm mapkubeapis -n drops timestore-api
helm mapkubeapis -n drops translations-api
helm mapkubeapis -n ebad ebad-api-timeseriesnetbas
helm mapkubeapis -n ebad metervalue-api
helm mapkubeapis -n ecp ecp-endpoint-dashboard
helm mapkubeapis -n ecp edx-toolbox-dashboard
helm mapkubeapis -n edna data-api
helm mapkubeapis -n edna data-web
helm mapkubeapis -n els api
helm mapkubeapis -n els web
helm mapkubeapis -n eltilsyn-extensions in-customerandequipment
helm mapkubeapis -n elvid elvid
helm mapkubeapis -n emif api
helm mapkubeapis -n emif market-api
helm mapkubeapis -n emif portal
helm mapkubeapis -n fairlight synthetic-timeseries-data-generator
helm mapkubeapis -n fakturadistribusjon ehf-api
helm mapkubeapis -n fleetmanagement admin
helm mapkubeapis -n fleetmanagement arcgis-api
helm mapkubeapis -n fleetmanagement cronjobs
helm mapkubeapis -n fleetmanagement engineer-api
helm mapkubeapis -n fleetmanagement guard-systems-reader
helm mapkubeapis -n fleetmanagement gui
helm mapkubeapis -n geonis-extensions in-annualconsumption
helm mapkubeapis -n geonis-extensions in-annualconsumption-intility
helm mapkubeapis -n geonis-extensions in-customer
helm mapkubeapis -n geonis-extensions in-customer-intility
helm mapkubeapis -n geonis-extensions in-equipment
helm mapkubeapis -n geonis-extensions in-equipment-intility
helm mapkubeapis -n geonis-extensions in-meter
helm mapkubeapis -n geonis-extensions in-meter-intility
helm mapkubeapis -n geonis-extensions in-pole
helm mapkubeapis -n geonis-extensions in-pole-intility
helm mapkubeapis -n hemmeligkunde hemmeligkunde-api
helm mapkubeapis -n hemmeligkunde hemmeligkunde-portal
helm mapkubeapis -n hes-extensions adhoc-response-api
helm mapkubeapis -n hes-extensions events-api
helm mapkubeapis -n hes-extensions events-spontaneous-api
helm mapkubeapis -n idgen api
helm mapkubeapis -n idgen portal
helm mapkubeapis -n idgen portal-api
helm mapkubeapis -n ifs-extensions document-api
helm mapkubeapis -n ifs-extensions in-customer
helm mapkubeapis -n ifs-extensions in-customer-intility
helm mapkubeapis -n ifs-extensions in-document
helm mapkubeapis -n ifs-extensions in-document-intility
helm mapkubeapis -n ifs-extensions in-equipment
helm mapkubeapis -n ifs-extensions in-equipment-intility
helm mapkubeapis -n ifs-extensions in-equipment-measurement
helm mapkubeapis -n ifs-extensions in-equipment-measurement-intility
helm mapkubeapis -n ifs-extensions in-lavspent-ncura
helm mapkubeapis -n ifs-extensions in-lavspent-ncura-intility
helm mapkubeapis -n ifs-extensions in-supportissue
helm mapkubeapis -n ifs-extensions in-workorder
helm mapkubeapis -n ifs-extensions in-workorder-intility
helm mapkubeapis -n ifs-extensions supportissue-api
helm mapkubeapis -n ifs-extensions supportissue-api-intility
helm mapkubeapis -n ifs-extensions workorder-api
helm mapkubeapis -n iss dummy-pushreceiver-api
helm mapkubeapis -n iss portal
helm mapkubeapis -n iss portal-api
helm mapkubeapis -n jordfeil dashboard
helm mapkubeapis -n jordfeil earthfaultevent-api
helm mapkubeapis -n jordfeil earthfaultstatistic-api
helm mapkubeapis -n jordfeil jordfeil-ui
helm mapkubeapis -n jordfeil jordfeillive
helm mapkubeapis -n jordfeil tickets-api
helm mapkubeapis -n kunde faktura-api
helm mapkubeapis -n kunde grid-tariff-api
helm mapkubeapis -n kunde kunde-api
helm mapkubeapis -n kunde kunde-slack-app
helm mapkubeapis -n kunde metervalue-api
helm mapkubeapis -n kunde metervalue-api-public
helm mapkubeapis -n kunde portal-api
helm mapkubeapis -n kunde poweroutage-api
helm mapkubeapis -n kunde slack-app
helm mapkubeapis -n kundeplattformpoc kundeplattformpoc
helm mapkubeapis -n kundeplattformpoc poc-api
helm mapkubeapis -n kvalitetsportalen dummy-pushreceiver-api
helm mapkubeapis -n kvalitetsportalen portal
helm mapkubeapis -n kvalitetsportalen portal-api
helm mapkubeapis -n leveransemotor motorapi
helm mapkubeapis -n leveransemotor motorweb
helm mapkubeapis -n louvre ai-vision-api
helm mapkubeapis -n louvre face-recognition-api
helm mapkubeapis -n louvre image-api
helm mapkubeapis -n louvre image-api-secure
helm mapkubeapis -n louvre imageenhance-api
helm mapkubeapis -n louvre imageimport-api
helm mapkubeapis -n louvre in-arcgisimages
helm mapkubeapis -n louvre louvre-web
helm mapkubeapis -n louvre plugin-handler-event-trigger-coordinator
helm mapkubeapis -n louvre plugin-organizer-api
helm mapkubeapis -n louvre smoketest
helm mapkubeapis -n mdmapi metervalue-api
helm mapkubeapis -n mdmapi timeseriesnetbas-api
helm mapkubeapis -n mdmx mdmx-ui
helm mapkubeapis -n mdmx vee-api
helm mapkubeapis -n mmm deliverysite-api
helm mapkubeapis -n mmm nettleie-inn
helm mapkubeapis -n mmm plikt-inn
helm mapkubeapis -n mmm portal-api
helm mapkubeapis -n mmm portal-web
helm mapkubeapis -n mmm tidsfrist-api
helm mapkubeapis -n msic api
helm mapkubeapis -n msic client
helm mapkubeapis -n msim api
helm mapkubeapis -n msim documentation-api
helm mapkubeapis -n msim msim-ui
helm mapkubeapis -n nettanalyse autonettmelding-api
helm mapkubeapis -n nettinfra avvik-arcgisimport
helm mapkubeapis -n nettinfra bildegjennomgang
helm mapkubeapis -n nettinfra bildegjennomgang-admin
helm mapkubeapis -n nettinfra bildegjennomgang-api
helm mapkubeapis -n nettinfra datascheduler-api
helm mapkubeapis -n nettinfra doktavla
helm mapkubeapis -n nettinfra doktavla-api
helm mapkubeapis -n nettinfra doktavla-worker
helm mapkubeapis -n nettinfra fleetmanagement-admin
helm mapkubeapis -n nettinfra fleetmanagement-cronjobs
helm mapkubeapis -n nettinfra fleetmanagement-engineer-api
helm mapkubeapis -n nettinfra fleetmanagement-guard-systems
helm mapkubeapis -n nettinfra fleetmanagement-gui
helm mapkubeapis -n nettinfra stikkledning
helm mapkubeapis -n nettinfra stikkledning-admin
helm mapkubeapis -n nettinfra stikkledning-image-admin
helm mapkubeapis -n nettinfra stikkledning-image-api
helm mapkubeapis -n nextin nextin
helm mapkubeapis -n nextin web
helm mapkubeapis -n quant-extensions in-networkasset
helm mapkubeapis -n quant-extensions in-networkasset-intility
helm mapkubeapis -n quant-extensions in-workorder
helm mapkubeapis -n quant-extensions in-workorder-intility
helm mapkubeapis -n quant-extensions in-workorderreport
helm mapkubeapis -n quant-extensions in-workorderreport-intility
helm mapkubeapis -n sesam-extensions aosjekk
helm mapkubeapis -n sesam-extensions in-telefoni
helm mapkubeapis -n sesam kafka-publisher
helm mapkubeapis -n slick slick-api
helm mapkubeapis -n slick slick-web
helm mapkubeapis -n sluttbrukeravbrudd api
helm mapkubeapis -n sluttbrukeravbrudd calculator
helm mapkubeapis -n sluttbrukeravbrudd ui
helm mapkubeapis -n sms sms-broker-poll
helm mapkubeapis -n sms sms-sender
helm mapkubeapis -n wms-extensions in-customermeterreading
helm mapkubeapis -n wms-extensions in-customermeterreading-intility
helm mapkubeapis -n wms-extensions in-workorder
helm mapkubeapis -n wms-extensions in-workorder-intility
