trigger:
  - '*'

pool:
  vmImage: "ubuntu-latest"

stages:
- stage: HelmPackage
  jobs:
    - job: Helm Package
      pool:
        vmImage: "ubuntu-latest"
      steps:
      
        - task: HelmDeploy@0
          displayName: Helm package
          inputs:
            command: package
            chartPath: elvia-deployment
            destination: $(Build.ArtifactStagingDirectory)

