trigger:
  - '*'

pool:
  vmImage: "ubuntu-latest"

stages:
- stage: HelmPackage
  jobs:
    - job: Package
      pool:
        vmImage: "ubuntu-latest"
      steps:
      
        - task: HelmDeploy@0
          displayName: Helm package
          inputs:
            command: package
            chartPath: elvia-deployment
            destination: $(Build.ArtifactStagingDirectory)
        # Generate kubernetes manifest from Helm chart
        - script: |
            helm package elvia-deployment > CI/test.tgz
            git add .
            git commit "Publish new package"
            git push origin trunk
          displayName: Generate kubernetes manifest from Helm chart

