trigger:
  - master

pool:
  vmImage: "ubuntu-latest"

variables:
  containerregistry: 'ContainerRegistryElvia'
  imagetag: "20210128.1"
  name: demo-api
  namespace: core

resources:
  repositories:
  - repository: templates
    type: github
    name: 3lvia/core-azure-devops-templates
    endpoint: 3lvia

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - task: PublishBuildArtifacts@1
      displayName: "Publish kubernetes configuration artifacts"
      inputs:
        PathtoPublish: CI
        ArtifactName: CI

- stage: DeployDev
  dependsOn: Build
  jobs:
  - template: deploy.yaml@templates
    parameters:
      environment: dev
      helmValuesFile: demo-api-values.yaml
