trigger:
  - master

pool:
  vmImage: "ubuntu-latest"

variables:
  containerregistry: 'ContainerRegistryElvia'
  namespace: core

resources:
  repositories:
  - repository: templates
    type: github
    name: 3lvia/core-azure-devops-templates
    endpoint: 3lvia

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - task: PublishBuildArtifacts@1
      displayName: "Publish kubernetes configuration artifacts"
      inputs:
        PathtoPublish: CI
        ArtifactName: CI
    - task: PublishBuildArtifacts@1
      displayName: "Publish helm chart"
      inputs:
        PathtoPublish: elvia-deployment
        ArtifactName: elvia-deployment
    
- stage: DeployStable
  dependsOn: Build
  jobs:
  - template: templates/deploy.yaml
    parameters:
      name: demo-api
      helmValuesFile: demo-api-values-stable.yaml
    
- stage: DeployProgressive
  dependsOn: DeployStable
  jobs:
  - template: templates/deploy.yaml
    parameters:
      name: demo-api
      helmValuesFile: demo-api-values-progressive.yaml
