apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ required "Missing .Values.name" .Values.name }}
  namespace: {{ required "Missing .Values.namespace" .Values.namespace }}
spec:
  replicas: {{ required "Missing .Values.replicaCount" .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ required "Missing .Values.name" .Values.name }}
      microservice-type: {{ required "Missing .Values.microserviceType" .Values.microserviceType }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ required "Missing .Values.name" .Values.name }}
        microservice-type: {{ required "Missing .Values.microserviceType" .Values.microserviceType }}
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: runtime/default
    spec:
      serviceAccountName: {{ required "Missing .Values.name" .Values.name }}
      imagePullSecrets:
      {{- if .Values.imagePullSecret }}
      - name: {{ .Values.imagePullSecret }}
      {{- else }}
      - name: containerregistryelvia
      {{- end}}
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
        supplementalGroups: [1001]
      {{- if .Values.dnsConfig }}
      dnsConfig: {{- toYaml .Values.dnsConfig | nindent 8 }} 
      {{- end}}
      {{- with .Values.hostAliases }}
      hostAliases: 
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ required "Missing .Values.name" .Values.name }}
        {{- with .Values.env }}
        env:
          {{- toYaml . | nindent 8 }}
        {{- end }}
        image: "{{ required "Missing .Values.image.repository" .Values.image.repository }}:{{ required "Missing .Values.image.tag" .Values.image.tag }}"
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        {{- with .Values.lifecycle }}
        lifecycle:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.readinessProbe }}
        readinessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.livenessProbe }}
        livenessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}

