kind: Service
apiVersion: v1
metadata:
  name: {{ required "Missing .Values.name" .Values.name }}
  namespace: {{ required "Missing .Values.namespace" .Values.namespace }}
  labels:
    app: {{ required "Missing .Values.name" .Values.name }}
spec:
  ports:
  - name: {{ required "Missing .Values.name" .Values.name }}port
    port: {{ required "Missing .Values.service.port" .Values.service.port }}
    {{- if .Values.service.targetPort }}
    targetPort: {{ .Values.service.targetPort -}}
    {{- end }}
  selector:
    app: {{ required "Missing .Values.name" .Values.name }}
