{{- if or (not .Values.serviceMonitor) (or .Values.serviceMonitor.enable (not (hasKey .Values.serviceMonitor "enable"))) -}}
kind: ServiceMonitor
apiVersion: monitoring.coreos.com/v1
metadata:
  name: {{ required "Missing .Values.name" .Values.name }}
  namespace: {{ required "Missing .Values.namespace" .Values.namespace }}
spec:
  endpoints:
  - port: {{ required "Missing .Values.name" .Values.name }}port
    {{- if .Values.serviceMonitor }}
    {{- if .Values.serviceMonitor.interval }}
    interval: {{ .Values.serviceMonitor.interval -}}
    {{- end }}
    {{- if .Values.serviceMonitor.honorLabels }}
    honorLabels: {{ .Values.serviceMonitor.honorLabels -}}
    {{- end }}
    {{- end }}
    {{- if .Values.serviceMonitor }}
    {{- with .Values.serviceMonitor.metricRelabelings }}
    metricRelabelings:
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- end }}
  selector:
    matchLabels:
      app: {{ required "Missing .Values.name" .Values.name }}
{{- end }}
