# Default values for elvia-deployment.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

name: github-repository-team-adder2
namespace: core
microserviceType: webapi
#environment: dev

replicaCount:
  dev: 1
  test: 1
  prod: 2

image:
  repository: containerregistryelvia.azurecr.io/core-github-repository-team-adder
  tag: "20201203.3"

imagePullSecret: containerregistryelvia

progressDeadlineSeconds: 60

securityContext:
  seccompProfile:
    type: RuntimeDefault
  runAsUser: 65532
  runAsGroup: 65532
  fsGroup: 65532
  supplementalGroups: [65532]

dnsConfig: 
  options:
  - name: single-request-reopen

hostAliases:
  - ip: "10.160.4.139"
    hostnames:
      - "haarcgeoevent01.hipad.no"
  - ip: "172.19.253.6"
    hostnames:
      - "haarcgeoevt01t1.hipad.no"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 400m
    memory: 500Mi
  prod:
    requests:
      cpu: 400m
      memory: 128Mi
    limits:
      cpu: 800m
      memory: 700Mi

nodePool: high-iops

# nodeSelector:
#   kubernetes.io/os: linux

# tolerations:
# - effect: NoSchedule
#   key: type
#   operator: Equal
#   value: high-iops

env: 
- name: ASPNETCORE_URLS
  value: http://+:8080
- name: my_key_from_config_map
  valueFrom:
    configMapKeyRef:
      key: bigtable.project
      name: github-repository-team-adder2
- name: my_key_from_secret
  valueFrom:
    secretKeyRef:
      key: mysecret
      name: github-repository-team-adder2

volumes:
- configMap:
    name: github-repository-team-adder2
  name: my-volume

volumeMounts:
- mountPath: /usr/share/nginx/html/assets/
  name: my-volume

service:
  port: 2112

ingress:
  subdomain: github-repository-team-adder
  path: "/"
  port: 2112


autoscaling:
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80

lifecycle:
  preStop:
    exec:
      command:
      - sleep
      - "15"

readinessProbe:
  failureThreshold: 3
  httpGet:
    path: /metrics
    port: 2112
    scheme: HTTP
  initialDelaySeconds: 15
  periodSeconds: 15
  successThreshold: 1
  timeoutSeconds: 3

livenessProbe:
  failureThreshold: 5
  httpGet:
    path: /metrics
    port: 2112
    scheme: HTTP
  initialDelaySeconds: 15
  periodSeconds: 15
  successThreshold: 1
  timeoutSeconds: 3

startupProbe:
  failureThreshold: 15
  httpGet:
    path: /metrics
    port: 2112
    scheme: HTTP
  initialDelaySeconds: 1
  periodSeconds: 1
  successThreshold: 1
  timeoutSeconds: 1

configmap:
  dev:
    bigtable.project: "hafslund-mdm-dev"
    bigtable.instanceid: "mdm-meterreadings-dev"
  test:
    bigtable.project: "hafslund-mdm-test"
    bigtable.instanceid: "mdm-meterreadings-test"
  prod:
    bigtable.project: "hafslund-mdm"
    bigtable.instanceid: "mdm-meterreadings"

# Always fetch secrets from Hashicorp Vault if possible
# We support kubernetes secrets for unusual deployments
secret:
  dev:
    mysecret: __SECRET_DEV__ # to be replaced in azure devops pipeline
  test:
    mysecret: __SECRET_TEST__ # to be replaced in azure devops pipeline
  prod:
    mysecret: __SECRET_PROD__ # to be replaced in azure devops pipeline

serviceMonitor:
  interval: 60s
  honorLabels: true