name: Publish Helm charts

on:
  push:
    branches: [master]

jobs:
  publish-helm-charts:
    name: Publish Helm charts
    runs-on: elvia-runner
    steps:
      - name: Get GitHub App token for repository
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: Package charts
        run: |
          helm package elvia-deployment
          helm package elvia-statefulset
          helm package iss-deployment

      - name: Index Helm repository
        run: helm repo index .

      - name: Push packaged charts to GitHub repository
        run: |
          if [[ -z "$(git status --porcelain)" ]]; then
            echo 'No changes to commit.'
            exit 0
          fi

          git config user.email '${{ vars.GH_APP_USER_EMAIL }}'
          git config user.name '${{ vars.GH_APP_USERNAME }}'

          git add .
          git commit -m 'Publish Helm charts'
          git push
