helm mapkubeapis -n drops archiver
helm mapkubeapis -n drops classification-worker
helm mapkubeapis -n drops classifiercorrelator
helm mapkubeapis -n drops drops-api
helm mapkubeapis -n drops drops-worker
helm mapkubeapis -n drops in-alarms-and-events
helm mapkubeapis -n drops indexer
helm mapkubeapis -n drops kpi-updater
helm mapkubeapis -n drops kpi-updater-alarmsandevents
helm mapkubeapis -n drops kpi-updater-amidevice
helm mapkubeapis -n drops kpi-updater-amisite
helm mapkubeapis -n drops kpi-updater-metervalues
helm mapkubeapis -n drops kpi-updater-radionetwork
helm mapkubeapis -n drops orchestrator
helm mapkubeapis -n drops worker
